#######
# Compiled from data/rvlcore/functions/load.mcscript
# to .//data/rvlcore/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function rvlcore:mcscript/load

tellraw @a {"text": "welcome, RVL Core started successfuly", "color": "blue", "bold": true}