#######
# Compiled from data/rvlcore/functions/main.mcscript
# to .//data/rvlcore/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# spawn randomizer by timer
function rvlcore:random/create_randomizer_timer
# ravakus crafting table functions
function rvlcore:crafting/set_table
function rvlcore:crafting/break_table
function rvlcore:crafting/table_mainloop
function rvlcore:crafting/standart_recipes