#######
# Compiled from data/rvlcore/functions/main.mcscript
# to .//data/rvlcore/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# spawn randomizer by timer
function rvlcore:random/create_randomizer_timer