#######
# Compiled from data/rvlcore/functions/load.mcscript
# to .//data/rvlcore/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######

# Extended from rvlcore/functions/random/random.mcscript
# to data/rvlcore/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add crtimer dummy
scoreboard objectives add random dummy
scoreboard objectives add tenConst dummy
