#######
# Compiled from rvlcore/functions/random/random.mcscript
# to .//data/rvlcore/functions/random/create_randomizer_timer.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/rvlcore/functions/random/random.mcscript
scoreboard players add crtimer crtimer 1
execute if score crtimer crtimer matches 100.. run execute as @a at @s run function rvlcore:random/create_randomizer
execute if score crtimer crtimer matches 100.. run scoreboard players set crtimer crtimer 0
