#######
# Compiled from rvlcore/functions/random/random.mcscript
# to .//data/rvlcore/functions/random/create_randomizer.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/rvlcore/functions/random/random.mcscript
kill @e[tag=randomizer]
scoreboard players set init random 0
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
summon minecraft:area_effect_cloud ~ ~ ~ {Tags:["randomizer"],Duration:2100000000}
scoreboard players add @e[tag=randomizer] random 1
scoreboard players set tenConst tenConst 10