#######
# Compiled from rvlcore/functions/random/random.mcscript
# to .//data/rvlcore/functions/random/get_random.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/rvlcore/functions/random/random.mcscript
scoreboard players set random random 0
execute if score iterator random matches 1.. run function rvlcore:random/update_random
