#######
# Compiled from rvlcore/functions/random/test_random.mcscript
# to .//data/rvlcore/functions/random/test_random.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set iterator random 2
function rvlcore:random/get_random
execute if score random random matches 50.. run say "random got"
