#######
# Compiled from rvlcore/functions/random/random.mcscript
# to .//data/rvlcore/functions/random/update_random.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/rvlcore/functions/random/random.mcscript
scoreboard players operation random random *= tenConst tenConst
scoreboard players operation random random += @e[type=area_effect_cloud,tag=randomizer,limit=1,sort=random] random
scoreboard players remove iterator random 1
execute if score iterator random matches 1.. run function rvlcore:random/update_random
