#######
# Compiled from rvlcore/functions/crafting/crafting_table.mcscript
# to .//data/rvlcore/functions/crafting/break_table.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/rvlcore/functions/crafting/crafting_table.mcscript
execute as @e[type=armor_stand, tag=rvl_table] at @s unless block ~ ~ ~ dropper run summon item ~ ~ ~ {Item:{id:"minecraft:bat_spawn_egg",Count:1b,tag:{display:{Name:'{"text":"rvl crafting table","italic":false}'},CustomModelData:2001,EntityTag:{id:"minecraft:armor_stand", NoGravity: 1b, Invulnerable: 1b, Invisible:1b, Tags:["rvl_table","temp"]}}}}
execute as @e[type=armor_stand, tag=rvl_table] at @s unless block ~ ~ ~ dropper run kill @s