#######
# Compiled from rvlcore/functions/crafting/table_loop.mcscript
# to .//data/rvlcore/functions/crafting/standart_recipes.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/rvlcore/functions/crafting/table_loop.mcscript
execute as @e[type=armor_stand, tag=rvl_table] at @s if block ~ ~ ~ dropper{Items:[{Slot:1b,id:"minecraft:iron_ingot",Count:1b},{Slot:3b,id:"minecraft:iron_ingot",Count:1b},{Slot:4b,id:"minecraft:blaze_powder",Count:1b},{Slot:5b,id:"minecraft:iron_ingot",Count:1b},{Slot:7b,id:"minecraft:iron_ingot",Count:1b}]} run data merge block ~ ~ ~ {Items:[{Slot:4b, id:"minecraft:iron_ingot", Count:1b, tag:{display:{Name:'{"text":"steel ingot","italic":"false"}'}, steelIngot:1b, CustomModelData:1}}]}