#######
# Compiled from rvlcore/functions/crafting/table_loop.mcscript
# to .//data/rvlcore/functions/crafting/table_mainloop.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//data/rvlcore/functions/crafting/table_loop.mcscript
execute as @e[type=armor_stand, tag=rvl_table] at @s align xyz run item replace entity @s armor.head with diamond_hoe{CustomModelData:2001}
execute as @e[type=armor_stand, tag=rvl_table] at @s align xyz run tp @s ~0.5 ~ ~0.5
execute as @e[type=armor_stand, tag=rvl_table] at @s align xyz run data modify entity @s Rotation set value 0